### ISSUE TITLE
ANM + NER 동시에 학습하는 모델 만들기

### ISSUE THREAD

**Issue by eubinecto** [pirates14/BERT#7]
## What?

ANM + NER 동시에 학습하는 모델 만들기

## Why? 

서로 다른 모델을  따로 만드는 것보다, 두 모델이 하고자하는 테스크를 동시에하면 성능이 더 높아질 수 있음을 기대가능

## How?

- BertForTokenClassification 도 nn.Module 이다  -  https://github.com/huggingface/transformers/blob/2aa3cd935d0f3bcd04ce66be6af4b760493d2ffe/src/transformers/modeling_utils.py#L412

- training_step에서 바로 로스를 계산 -  https://github.com/pirates14/BERT/blob/64f12aad284abb5d0a4f2c151f33018f30813496/Test/main_test.py#L104-L105

```python3


ner_model = BERTForTokenClassification.from_pretrained(....)
ner_model 
type(model) -> nn.Module  


anm_model = BERTForTokenClassification.from_pretrained(...)
anm_model
type(anm_model) -> nn.Module


class BERT(nn.Module):

  def __init__(self, ner_model, anm_model):
    # 이 친구들도 결국엔 nn.Module이라서, BERT를 학습하면, 이 친구들도 최적화
     self.ner_model = ner_model
     self.anm_model = anm_model


  

   def training_step(self, X, y) -> torch.Tensor:
      output_1 = self.ner_model(..... X, y...)
      output_2 = self.anm_model(... X, y...)
      loss_1 =  output_1[0]
      loss_2 = output_2[0]
     return loss_1  + loss_2


```

## To-do's
- [x] `anm_model` 과 `ner_model`을 일단 따로 학습시키는 걸 성공 (i.e. 다 학습데이터에 대해서는 학습 정확도가 100에 가깝게)
- [x] `BERT` 모델의 학습정확도 100에 가깝게 

효율적인 디자인은  여기까지 완료후 적용.
여기부터는 로컬에서는 힘들고, gpu가 필요할 것.
pytorch-lightning
- [ ]  데이터를 늘려서 더 큰 데이터도 학습정확도가 100에 가깝게 나오는지
- [ ] train / val /  test -> test에서 잘 나오는지

.....
-   BERT vs. `anm_model` &  `ner_model`
-  wandb 적용.
